#cloud-config
package_update: true
package_upgrade: true

packages:
  - nginx
  - certbot
  - python3-certbot-nginx

write_files:
  - path: /etc/pyron/configure-server
    content: |
      first-run=true
  - path: /root/deploy.sh
    permissions: '0755'
    content: |
      ${indent(6, deploy_script)}

runcmd:
  - /root/deploy.sh
