name: Build and Deploy
on:
  push:
    branches: [master]
    paths:
      - "app/**" 
      - ".github/workflows/app.yaml"
  pull_request:
    branches: [master]
    paths:
      - "app/**" 
      - ".github/workflows/app.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: pyron-api:${{ github.sha }}
    defaults:
      run:
        working-directory: app/
    steps:
      - name: Checking out the code...
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Login to Digital Ocean Registry..
        run: doctl registry login
      - name: Setting up QEMU...
        uses: docker/setup-qemu-action@v3
      - name: Setting up Docker Buildx...
        uses: docker/setup-buildx-action@v3
      - name: Building...
        run: docker build -t registry.digitalocean.com/pyron-api-lon1/pyron-api:${{ github.sha }} .
      - name: Tagging and Pushing...
        run: | 
          docker images &&
          docker push registry.digitalocean.com/pyron-api-lon1/pyron-api:${{ github.sha }}